### ISSUE TITLE
in-repo

### ISSUE THREAD

**Issue by betocantu93** [dfreeman/ember-css-modules-sass#23]
Hello, how could I access app.scss sass variables, like `$primary: 'blue'`, and `ember-paper` specific stuff from an in-repo-addon module? I'm creating a styleguide as an in-repo-addon inside an app which uses ember-paper

#### components/info-message.scssm

```css
.container {
 background: paper-color($primary, '500');
}
```

`paper-color` is a sass func provided by `ember-paper`
$primary is a sass variable defined in app/styles/app.scss in the parent app.

and in my in-repo-addon module if I use `$primary` it crashes, because `$primary` is undefined.

Normal in-repo-addons can access both without trouble

I don't know if this in-repo-addon needs to depend on ember-paper (which normal non ECM in-repo-addons, don't), or if its something about cssModules configuration or if I would need to limit myself to maybe expose these as css variables like

```css
.container {
  background: rgba(var(--primary-500));
}
```

Thanks in advance, my config is ember-css-modules + ember-css-modules-sass in the main app with
```ts
cssModules: {
      intermediateOutputPath: 'app/styles/_modules.scss',
      extension: 'scssm'
    }
```

and in the in-repo, plain defaults...
